--
--
--
-- insert into worker (id, name, lastname, pass)
--         values
--             (1, 'Имя1', 'Фамилия', 'password'),
--             (2, 'Имя2', 'Фамилия', 'password'),
--             (3, 'Имя3', 'Фамилия', 'password'),
--             (4, 'Имя4', 'Фамилия', 'password'),
--             (5, 'Имя5', 'Фамилия', 'password'),
--             (6, 'Имя6', 'Фамилия', 'password'),
--             (7, 'Имя7', 'Фамилия', 'password'),
--             (8, 'Имя8', 'Фамилия', 'password'),
--             (9, 'Имя9', 'Фамилия', 'password'),
--             (10, 'Имя10', 'Фамилия', 'password');
--
-- insert into user_role (user_id, roles)
--     values
--         (1, 'awe')
--
--
-- select name, pass from worker where name = 'Имя1';
-- select name, pass from worker where name = 'Имя', pass = 'password';
--
